Feature darkmode managment
devs-coffee/frontend-collab-chat-project pull request #62
Opened 2023-08-07 12:27 UTC by Jerome-Marichez

The Feature: 
__________________
Our app supports toggling between dark and light themes, and it takes into account the user's browser/OS preferences to determine which theme to display when local storage is not available. The custom hook is designed to run only once when the <Header/> component is loaded or when the setDarkMode function is called. It does not re-run with every render, ensuring optimal performance.

About useDarkMode.ts
__________________
Created a Hook so it return the darkMode value as a boolean.

- True if it's a dark theme false otherwise

- darkMode will check for localstorage and look at "theme" value to return true for darkMode value.

- If no localstorage then darkMode value will be set depend of Theme/OS Prefs.

The hook return too a setDarkMode to directly enable darkMode.

About Header.tsx/DarkModeSwitch.tsx
__________________
- Maked DarkModeSwitch more short & clear

- DarkModeSwitch accepts "darkMode" as a boolean prop and "setDarkMode" as a SetState function prop. (In our example, we pass the state and setState values obtained from our custom hook useDarkMode.)

- This approach allows DarkModeSwitch to function as a PureComponent, avoiding re-running the hook every time an onChange event occurs."

2023-08-08 19:07 UTC, julienb86 commented
Il faudrait prendre en compte le dev fait côté back sur les prêts, il faut voir avec Whitedog pour qu'il te donne les éléments.. aussi attention tu allais faire ta pr sur main . Les devs donc les pr se font sur la branche dev. J ai redirigé ta pr

2023-08-13 06:05 UTC, WhitedogWarren commented on src/components/template/header/Header.tsx
>  export default function Header({ ioClose }: any) {
Ce 'any', on peut peut-être faire quelque chose.
Je pense que c'est une fonction qui retourne void.

2023-08-13 06:06 UTC, WhitedogWarren commented on src/components/template/header/Header.tsx
>      const authStatus = useSelector((state: any) => state.authStatus);
Pareil pour celui-là, j'ai déjà corriger à un ou deux endroits.

2023-08-13 06:12 UTC, WhitedogWarren commented on src/components/template/header/Header.tsx
> +            const requestTheme: string = user.prefs.colorScheme.toUpperCase();
Pourquoi le upperCase() ici ?
On pourrait faire directement la comparaison, non ?
user.prefs.colorScheme === "dark" ? setDarkmode(true) : setDarkMode(false)

2023-08-13 06:14 UTC, WhitedogWarren commented on src/interfaces/ITheme.ts
C'est un enum, pas une interface, le nom du fichier devrait être theme.enum.ts

2023-08-13 06:18 UTC, WhitedogWarren commented on src/interfaces/IUser.tsx
> +        colorScheme: Theme | "LIGHT" | "DARK";
l'enum Theme renvoie "dark" ou "light" en lowerCase.
Ici il faudrait de la cohérence, et ne faire l'upperCase() qu'au moment de faire la requête.
Ou alors faire comme côté back, mettre du uppercase dans l'enum.

2023-08-13 06:19 UTC, WhitedogWarren commented on src/services/userService.tsx
> +import { User, Prefs } from "../interfaces/IUser";
User extends Prefs, du coup a-t-on besoin d'importer les deux ?

2023-08-13 06:21 UTC, WhitedogWarren requested changes
Beau boulot !!!
Bon, il y a un ou deux trucs qu'on pourrait retravailler.

2023-08-13 08:00 UTC, Jerome-Marichez commented on src/interfaces/ITheme.ts
Oui ça me semble logique.

2023-08-13 08:19 UTC, Jerome-Marichez commented on src/components/template/header/Header.tsx
>  export default function Header({ ioClose }: any) {
En effet on peux mieux typer de cette façon ```export default function Header({ ioClose }: { ioClose: () => void }): JSX.Element```

2023-08-13 10:01 UTC, Jerome-Marichez commented
Normalement c'est fix avec ce qui à était demandée :)

2023-08-13 12:16 UTC, julienb86 approved these changes

2023-08-13 12:17 UTC, merged