Refactor message error
devs-coffee/frontend-collab-chat-project pull request #83
Opened 2023-08-24 09:43 UTC by Jerome-Marichez

- Created a new component <MessageError/> who wrap a <Snackbar/> and re-use the logic.

2023-08-26 08:04 UTC, julienb86 approved these changes

2023-08-27 06:49 UTC, WhitedogWarren commented on src/components/Auth/Login/Login.tsx
> +import { MessageError } from '../../index';
le mot "index' est inutile

2023-08-27 06:49 UTC, WhitedogWarren commented on src/components/Auth/Signup/Signup.tsx
> +import { Modal, AvatarCropper, MessageError } from '../../index';
index inutile

2023-08-27 06:50 UTC, WhitedogWarren commented on src/components/ChannelCreationForm/ChannelCreationForm.tsx
> +import { MessageError } from '../MessageError/MessageError';
Tu devrais utiliser ton index pour simplifier la référence de l'import.

2023-08-27 06:51 UTC, WhitedogWarren commented on src/components/ChannelUpdateForm/ChannelUpdateForm.tsx
> +import { MessageError } from '../../components';
L'adresse d'import est-elle bonne ?

2023-08-27 06:52 UTC, WhitedogWarren commented on src/components/Message/Message.tsx
> +import { MessageEditor, Actions, MessageError } from '../index';
index inutile

2023-08-27 06:52 UTC, WhitedogWarren commented on src/components/MessageBox/MessageBox.tsx
> +import { MessageEditor, MessageList, MessageError } from "../index";
index inutile

2023-08-27 06:53 UTC, WhitedogWarren commented on src/components/MessageList/MessageList.tsx
> +import { MessageError } from '../index';
index inutile

2023-08-27 06:54 UTC, WhitedogWarren commented on src/components/MessageList/MessageList.tsx
> +        ;
Pourquoi une instruction vide ?

2023-08-27 06:54 UTC, WhitedogWarren commented on src/components/ServerCreationForm/ServerCreationForm.tsx
> +import { AvatarCropper, Search, MessageError } from '../index';
index inutile

2023-08-27 06:55 UTC, WhitedogWarren commented on src/components/ServerDisplay/ServerMembersBox/ServerMembersBox.tsx
> +import { UserItem, MessageError } from "../../../components";
Revoir l'adresse d'import

2023-08-27 06:56 UTC, WhitedogWarren commented on src/components/ServerSearching/ServerSearching.tsx
> +import { MessageError } from '../../components';
adresse d'import

2023-08-27 06:57 UTC, WhitedogWarren commented on src/components/ServerUpdateForm/ServerUpdateForm.tsx
> +import { Modal, AvatarCropper, Search, MessageError } from '../../components';
adresse d'import

2023-08-27 06:57 UTC, WhitedogWarren commented on src/pages/Profile/Profile.tsx
> +import { Modal, AvatarCropper, MessageError } from '../../components';
adresse d'import

2023-08-27 06:57 UTC, WhitedogWarren commented on src/pages/ServerDisplay/ServerDisplay.tsx
> +import { ServerHeading, ServerChat, ServerChannelBox, ServerMembersBox, ServerUpdateForm, MessageError } from "../../components";
adresse d'import

2023-08-27 07:02 UTC, WhitedogWarren requested changes
Beau boulot.
Il y a juste toutes les adresses d'import à corriger.
Grâce à ton système d'index, moi je fais juste :
import { AnyComponent } from '../';

2023-08-27 07:02 UTC, WhitedogWarren commented on src/pages/ServerDisplay/ServerDisplay.tsx
> +import { ServerHeading, ServerChat, ServerChannelBox, ServerMembersBox, ServerUpdateForm, MessageError } from "../../components";
Autant pour moi, pour les pages tu as la bonne adresse ^^

2023-08-27 07:03 UTC, WhitedogWarren commented on src/pages/Profile/Profile.tsx
> +import { Modal, AvatarCropper, MessageError } from '../../components';
Erreur de ma part

2023-08-27 09:34 UTC, WhitedogWarren approved these changes
Je me suis permis de corriger les adresses d'imports, ainsi que le login ( ça c'était un oubli de ma part )

2023-08-27 09:42 UTC, merged