Feature handle private messages
devs-coffee/frontend-collab-chat-project pull request #84
Opened 2023-08-26 08:48 UTC by WhitedogWarren

2023-08-26 17:05 UTC, julienb86 requested changes

2023-08-26 17:05 UTC, julienb86 commented on src/components/MessageList/MessageList.tsx
> +      new ChannelService().markAsRead(channelId);
il manque un try catch ici

2023-08-26 17:05 UTC, julienb86 commented on src/components/MessageList/MessageList.tsx
> +    if(elt?.scrollTop === elt?.scrollHeight! - elt?.offsetHeight!) {
pourquoi faire ça et mettre un console log, je ne comprends pas

2023-08-26 17:05 UTC, julienb86 commented on src/pages/PrivateMessages/PrivateMessages.tsx
> +                    <p key={`private_${chan.users[0].user.id}`} onClick={() => {setChannelId(chan.id)}}>{chan.users[0].user.pseudo}</p>
la key sera toujours la meme non?

2023-08-26 17:05 UTC, julienb86 commented on src/pages/UserDisplay/UserDisplay.tsx
> +        await messageService.send(message);
il faudrait un try catch ici

2023-08-26 17:05 UTC, julienb86 commented on src/services/channelService.ts
> +    //TODO créer interface PrivateChannel
le TODO est fait déjà, du coup on peut remplacer le any ici

2023-08-27 14:13 UTC, WhitedogWarren commented on src/components/MessageList/MessageList.tsx
> +      new ChannelService().markAsRead(channelId);
Done

2023-08-27 14:17 UTC, WhitedogWarren commented on src/components/MessageList/MessageList.tsx
> +    if(elt?.scrollTop === elt?.scrollHeight! - elt?.offsetHeight!) {
C'est en préparation d'une future PR.
Le but, ce serait de ne pas scroller d'entrée de jeu vers le dernier message de la liste, mais vers le premier message non lu. Ici, j'ai créé un trigger pour télécharger plus de messages non lus ou pour mettre à jour le lastRead du channel.

2023-08-27 14:20 UTC, WhitedogWarren commented on src/pages/PrivateMessages/PrivateMessages.tsx
> +                    <p key={`private_${chan.users[0].user.id}`} onClick={() => {setChannelId(chan.id)}}>{chan.users[0].user.pseudo}</p>
Non, l'id sera différente pour chaque chan. Par contre, il y a toujours ce users.user[0] qui perturbe, "users" étant en réalité un userChannel.
Mais cette structure peut être exploitable si on implémente un channel privé pouvant avoir plus de deux membres.

2023-08-27 14:27 UTC, julienb86 commented on src/components/MessageList/MessageList.tsx
> +    if(elt?.scrollTop === elt?.scrollHeight! - elt?.offsetHeight!) {
Ok mais pourquoi ne pas mettre le code dans la PR prévue dans ce cas

2023-08-27 14:36 UTC, WhitedogWarren commented on src/components/MessageList/MessageList.tsx
> +    if(elt?.scrollTop === elt?.scrollHeight! - elt?.offsetHeight!) {
Oui, je sais, tu m'as déjà fait la remarque ^^
La PR n'est pas encore commencée. J'ai juste inspecté sur la manière de trigger le scroll vers le bas de page. Or actuellement, on le fait automatiquement d'entrée de jeu.
J'ai mis le console.log en commentaire.

2023-08-27 14:50 UTC, WhitedogWarren commented on src/services/channelService.ts
> +    //TODO créer interface PrivateChannel
Done

2023-08-27 15:45 UTC, julienb86 approved these changes

2023-08-27 15:45 UTC, merged